[tool.poetry]
name = "dsa-2024"
version = "0.1.0"
description = ""
authors = ["ImtiazKhanDS <imtiaz.khan.bds@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
platformdirs = "^4.3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
